"use client";

import { useState } from "react";
import type { Finding } from "../../lib/fixes";

const DETECTOR_LABELS: Record<Finding["detector"], string> = {
  axe: "Measured by axe-core",
  heuristic: "Observed by keyboard and layout checks",
  ai: "AI suggestion — verify before acting",
};

function CopyButton({ text, label, ariaLabel }: { text: string; label: string; ariaLabel?: string }) {
  const [copied, setCopied] = useState(false);

  async function copy() {
    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  }

  return <button aria-label={ariaLabel} onClick={copy}>{copied ? "Copied" : label}</button>;
}

function Evidence({ finding, advisory }: { finding: Finding; advisory: boolean }) {
  return (
    <div className="occurrences-block">
      <div className="subheading"><h3>Evidence</h3><span>Showing {finding.occurrences.length} of {finding.count}</span></div>
      {finding.occurrences.map((occurrence, index) => (
        <div className="occurrence" key={occurrence.selector}>
          <div className="occurrence-top"><span>Element {index + 1}</span><code>{occurrence.selector}</code></div>
          <div className="code-block"><code>{occurrence.html}</code><CopyButton text={occurrence.html} label="Copy" ariaLabel="Copy HTML snippet" /></div>
          <p><b>{advisory ? "What axe reported:" : "Why it failed:"}</b> {occurrence.failure}</p>
        </div>
      ))}
    </div>
  );
}

function FixPanel({ fix }: { fix: Finding["fix"] }) {
  const usedModel = Boolean(fix.provider) && fix.provider !== "deterministic";
  return (
    <div className="ai-fix">
      <div className="ai-fix-head"><span className="ai-badge"><i>✦</i> {usedModel ? "AI-assisted fix" : "Standard guidance"}</span><span className={`confidence confidence-${fix.confidence}`}>{fix.confidence} confidence</span></div>
      <h3>{fix.summary}</h3>
      <p>{fix.whyItMatters}</p>
      <ol>{fix.steps.map((step) => <li key={step}>{step}</li>)}</ol>
      {fix.codeExample && (
        <div className="fix-code">
          <div><span>Suggested example</span><span>HTML / CSS</span></div>
          <pre><code>{fix.codeExample}</code></pre>
          <CopyButton text={fix.codeExample} label="Copy example" />
        </div>
      )}
      {fix.requiresManualReview && <div className="review-note"><span aria-hidden="true">!</span><p><b>Manual review required.</b> Confirm this fix matches the element’s purpose and test it with assistive technology.</p></div>}
      {fix.model && <p className="fix-provenance">{fix.provider === "deterministic" ? "Deterministic axe and WCAG guidance — no model was used." : `Generated by ${fix.model}. Always review before shipping.`}</p>}
    </div>
  );
}

/** One rule group. Shared by the violations list and the advisory list. */
export function FindingCard({ finding, open }: { finding: Finding; open: boolean }) {
  const advisory = finding.kind === "advisory";
  const tone = advisory ? "advisory" : finding.impact;

  return (
    <details className={`finding-card impact-${finding.impact}${advisory ? " advisory-card" : ""}`} open={open}>
      <summary>
        <span className={`severity-symbol ${tone}-bg`}>{advisory ? "i" : "!"}</span>
        <span className="finding-title"><b>{finding.title}</b><small>{finding.count} affected {finding.count === 1 ? "element" : "elements"} · {finding.ruleId}</small></span>
        <span className={`impact ${tone}-text`}>{tone}</span>
        <span className="chevron" aria-hidden="true">⌄</span>
      </summary>
      <div className="finding-detail">
        <div className="finding-explanation">
          <div className="finding-meta">
            {finding.context && <span className="meta-chip">{finding.context}</span>}
            <span className={`meta-chip detector-${finding.detector}`}>{DETECTOR_LABELS[finding.detector]}</span>
          </div>
          <p>{finding.explanation}</p>
          {finding.wcag.length > 0 && (
            <div className="wcag-links"><span>{advisory ? "Reference" : "WCAG references"}</span>{finding.wcag.map((item) => <a key={item.label} href={item.href} target="_blank" rel="noreferrer">{item.label} ↗</a>)}</div>
          )}
        </div>
        <Evidence finding={finding} advisory={advisory} />
        <FixPanel fix={finding.fix} />
      </div>
    </details>
  );
}
