/**
 * Representative axe-core rule groups used while the isolated Playwright/axe
 * worker is not connected. Findings only — remediations are generated by the
 * configured fix provider (see `lib/fixes`).
 *
 * Single source of truth: both the worker and the client fallback read this, so
 * the preview data cannot drift between them. Delete this module once the real
 * scanner writes normalized results.
 */
import type { FindingInput } from "../fixes/types";

const wcag = (label: string, slug: string) => [{ label, href: `https://www.w3.org/WAI/WCAG22/Understanding/${slug}.html` }];

export function representativeFindings(): FindingInput[] {
  return [
    {
      ruleId: "button-name",
      impact: "critical",
      title: "Buttons must have discernible text",
      count: 2,
      explanation: "Two icon-only buttons have no accessible name. Screen-reader users hear only “button” and cannot tell what each control does.",
      wcag: wcag("4.1.2 Name, Role, Value", "name-role-value"),
      occurrences: [
        { selector: ".site-header > button.cart-toggle", html: "<button class=\"cart-toggle\"><span class=\"cart-icon\"></span></button>", failure: "Element does not have inner text that is visible to screen readers, an aria-label, or an aria-labelledby attribute." },
        { selector: ".search-panel > button.close", html: "<button class=\"close\"><span aria-hidden=\"true\">×</span></button>", failure: "Element does not have an accessible name." },
      ],
    },
    {
      ruleId: "color-contrast",
      impact: "serious",
      title: "Text must meet minimum color contrast",
      count: 12,
      explanation: "Several text elements do not have enough contrast against their backgrounds, making them difficult to read for people with low vision.",
      wcag: wcag("1.4.3 Contrast (Minimum)", "contrast-minimum"),
      occurrences: [
        { selector: ".product-card .eyebrow", html: "<span class=\"eyebrow\">New arrival</span>", failure: "Element has insufficient color contrast of 2.61:1. Expected 4.5:1 for this text size." },
        { selector: ".footer .legal-link", html: "<a class=\"legal-link\" href=\"/returns\">Returns</a>", failure: "Element has insufficient color contrast of 3.02:1. Expected 4.5:1." },
      ],
    },
    {
      ruleId: "image-alt",
      impact: "serious",
      title: "Images must have alternative text",
      count: 3,
      explanation: "Three images are missing alt attributes. Their purpose cannot be determined from markup alone.",
      wcag: wcag("1.1.1 Non-text Content", "non-text-content"),
      occurrences: [
        { selector: ".hero-promo > img", html: "<img src=\"/summer-collection.webp\">", failure: "Element does not have an alt attribute." },
        { selector: ".product-card:nth-child(2) img", html: "<img src=\"/linen-shirt.webp\">", failure: "Element does not have an alt attribute." },
      ],
    },
    {
      ruleId: "label",
      impact: "serious",
      title: "Form inputs must have labels",
      count: 4,
      explanation: "Four fields are missing programmatically associated labels, so their purpose may be unclear outside the visual layout.",
      wcag: wcag("3.3.2 Labels or Instructions", "labels-or-instructions"),
      occurrences: [
        { selector: "#newsletter-email", html: "<input id=\"newsletter-email\" type=\"email\" placeholder=\"Email address\">", failure: "Form element does not have an implicit or explicit label." },
        { selector: "#search-products", html: "<input id=\"search-products\" type=\"search\">", failure: "Form element does not have an accessible name." },
      ],
    },
    {
      ruleId: "html-has-lang",
      impact: "moderate",
      title: "The page must declare a language",
      count: 1,
      explanation: "The html element has no lang attribute. Screen readers may use the wrong pronunciation rules.",
      wcag: wcag("3.1.1 Language of Page", "language-of-page"),
      occurrences: [
        { selector: "html", html: "<html>", failure: "The <html> element does not have a lang attribute." },
      ],
    },
  ];
}
